### PR TITLE
Changes for AnVIL workspace to be created

### PR DESCRIPTION
**Pull request by Kayla-Morrell**
Hi @lmweber! I'm creating this pull request after attempting to create an AnVIL workspace from this book. There were some things I had to change in the DESCRIPTION file to get `AnVILPublish::as_workspace()` to run successfully. One of the main issues was the name of the repo since it's not a proper package name. I ended up renaming my local version of the forked repo to OSTAbook. These were the changes I made to the DESCRIPTION file:

- Rename repo/package so it's a proper package name (without hyphen)
- Add authors/maintainers
- Add a date

Let me know if you need any clarification or have any questions.

### CODE REVIEW

**Comment by lcolladotor** [comment]
Hi Kayla,

With the changes I made at https://github.com/lmweber/OSTA-book/pull/11, we won't need the changes you made. I realized this later, since I had to edit the `DESCRIPTION` file to enable caching of R packages on GitHub actions. So well, we both needed a proper `DESCRIPTION` file ;)

Best,
Leo

**Comment by Kayla-Morrell** [comment]
Hi Leo,

Sounds good to me! Thanks for following up. Glad to see the changes were made :)

**Comment by lmweber** [comment]
Thanks @Kayla-Morrell and @lcolladotor ! I think with @lcolladotor 's updates from yesterday this should now work, so will close this pull request.

**Comment by lmweber** [comment]
Ah thanks - just clicked at the same time!

**Pull request closed without merging**
